---
version: '2'

services:
  redis:
    image: redis:3.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  api:
    image: janna:latest
    command: rackup -s puma --host 0.0.0.0 -p 4567 config.ru
    restart: unless-stopped
    env_file: .env
    ports:
      - '4567:4567'
    environment:
      RACK_ENV: production
    depends_on:
      - 'redis'

  worker:
    image: janna:latest
    command: bundle exec sidekiq -r ./janna.rb
    restart: unless-stopped
    env_file: .env
    volumes:
      - 'data:/data'
    environment:
      RACK_ENV: production
    depends_on:
      - 'redis'
      - 'api'

volumes:
  data:
